export const labels = {
  es: {
    subtitle: 'Servicios de transportación terrestre',
    orderHeader: 'Su orden de viaje ha sido confirmada.',
    reservationHeader:
      'Su reservación de viaje ha sido confirmada. Por favor pague en efectivo el monto a deber una vez que contacte a nuestros representantes.',
    order: 'Orden',
    orderDetails: 'Detalles de la orden',
    client: 'Cliente',
    tripType: 'Tipo de viaje',
    'round-trip': 'Viaje redondo',
    airport: 'Viaje al aeropuerto',
    hotel: 'Viaje al hotel',
    payment: 'Pago',
    transportationServices: 'Servicios de transportación',
    additionals: 'Adicionales',
    reservation: 'Reservación',
    amountDue: 'Monto a deber',
    arrivalFlight: 'Vuelo de llegada',
    departureFlight: 'Vuelo de salida',
    grownups: 'Grandes',
    children: 'Niños',
    infants: 'Infantes',
    vehicle: 'Vehículo',
    vehicleType: 'Tipo de vehículo',
    private: 'Privado',
    shared: 'Compartido',
    SHOPPING: 'Compras',
    CARSEAT: 'Silla para bebés',
    BOOSTERSEAT: 'Asiento de niño',
    WHEELCHAIR: 'Silla de ruedas',
    PETBOX: 'Caja de mascota',
    KAYAK: 'Kayak',
    BICYCLE: 'Bicicleta',
    SURFTABLE: 'Tabla de surf',
    internationalArrival: 'Llegadas internacionales',
    driverIntro: `Éste le presentará a su chofer que lo llevará a su hotel, villa o destino en Los Cabos a bordo de nuestras unidades de lujo donde se le brindará una botella de agua fría por pasajero de cortesía.`,
    internationalArrivalText: (s: string) =>
      `Una vez que aterrice en el Aeropuerto Internacional de Los Cabos (SJD), pase el control de migración y recoja su equipaje. Localice el área de transportación terrestre en la Sombrilla 4, donde nuestro representante en el aeropuerto estará esperándolo con un letrero con ${s}. ${labels.es.driverIntro}`,
    nationalArrival: 'Llegadas nacionales',
    nationalArrivalText: (s: string) =>
      `Una vez que aterrize en el Aeropuerto de Los Cabos (SJD) y recoja su equipaje, tome la "Salida de Grupos", donde un representante lo estará esperando con un letrero con ${s}. ${labels.es.driverIntro}`,
    yourName: 'su nombre',
    settur: 'el nombre SETTUR',
    tolerance:
      'El tiempo de tolerancia una vez que aterriza su avión es de 50min.',
    weWaiting:
      'Estaremos monitoreando su vuelo, por lo que si se demora o adelanta lo sabremos, ¡estaremos esperándolo!',
    departures: 'Salidas',
    departureText:
      'Se recomienda llegar al aeropuerto 2 horas antes en vuelos Nacionales y 3 horas antes en vuelos Internacionales, considere el tiempo de traslado. La hora de salida la asigna el sistema automáticamente. Nuestros representantes se le confirmarán antes de su salida.',
    departureInstructions:
      'El chofer de su transporte de lujo lo buscará en el lobby de su Hotel o bien tocará a la puerta de su Villa 10 minutos antes de la hora de salida indicada. El tiempo de tolerancia es de 10 minutos después de la hora de salida señalada. Le pedimos sea puntual. Fuera de este horario se considerará que no se presentó a su cita y la unidad se retirará sin pasajeros.',
    changes:
      'Si requiere hacer cambios o tiene solicitudes adicionales contáctenos al teléfono',
    orMail: 'o envíe un mail a',
    timeOpen: 'Lunes a viernes de 09:00 AM a 06:00 PM',
    footer: 'Gracias por su preferencia. Por favor NO RESPONDA a este correo.',
  },
  en: {
    subtitle: 'Ground transportation services',
    orderHeader: 'Your order is confirmed.',
    reservationHeader:
      'Your reservation is confirmed. Please pay the amount due in cash once you contact one of our representatives.',
    order: 'Order',
    orderDetails: 'Order Details',
    client: 'Client',
    tripType: 'Trip type',
    'round-trip': 'Round Trip',
    airport: 'To the airport',
    hotel: 'To the hotel',
    payment: 'Payment',
    transportationServices: 'Transportation services',
    additionals: 'Additionals',
    reservation: 'Reservation',
    amountDue: 'Amount due',
    arrivalFlight: 'Arrival flight',
    departureFlight: 'Departure flight',
    grownups: 'Grown-ups',
    children: 'Children',
    infants: 'Infants',
    vehicle: 'Vehicle',
    vehicleType: 'Vehicle Type',
    private: 'Private',
    shared: 'Shared',
    SHOPPING: 'Shopping',
    CARSEAT: 'Car Seat',
    BOOSTERSEAT: 'Booster Seat',
    WHEELCHAIR: 'Wheelchair',
    PETBOX: 'Pet Box',
    KAYAK: 'Kayak',
    BICYCLE: 'Bicycle',
    SURFTABLE: 'Surf Table',
    internationalArrival: 'International Arrival',
    driverIntro:
      'He will introduce you to the driver that will take you to your hotel, villa or destination in Los Cabos on our premium cars. Each passenger will get a cold bottle of water.',
    internationalArrivalText: (s: string) =>
      `After you land in the International Los Cabos Airport (SJD), go through immigration and pick your baggage. Find the ground transportation area and you'll find our representative in tent 4 with a sign with ${s}. ${labels.en.driverIntro}`,
    nationalArrival: 'National Arrival',
    nationalArrivalText: (s: string) =>
      `After you land and pick your baggage, go to the "Salida de Grupos" (Groups' Exit). One of our representatives will be waiting with a sign with ${s}. ${labels.en.driverIntro}`,
    yourName: 'your name',
    settur: 'the name SETTUR',
    tolerance: 'The tolerance time after your flight lands is of 50min.',
    weWaiting:
      "We will be monitoring your flight. If it gets delayed we will be waiting, don't worry.",
    departures: 'Departures',
    departureText:
      "We encourage you to arrive to the airport 2 hours in advance for National flights and 3 hours in advance for International flights. Please consider the time you'll take from your hotel to the airport. The departure pick up is assigned by the system. Our representatives will confirm you the pick up time before your departure.",
    departureInstructions:
      "The driver of our premium units will find you in the lobby of your hotel or will call you on your Villa 10 minutes before the pick up time. The tolerance time is of 10 minutes after your pick up time. We encourage you to be on time. If our driver can't find you after the tolerance time it will be considered a NO SHOW and the unit will leave without passengers.",
    changes:
      'If you need to make changes or have additional requests please contact us to',
    orMail: 'or send an email to',
    timeOpen: 'Monday - Friday. 09:00 AM to 06:00 PM Local Time',
    footer: 'Thanks for your preference. Please DO NOT REPLY to this email.',
  },
}
